ARG NVVERSION

FROM home/nv:${NVVERSION}  as runenv

ENV DEBIAN_FRONTEND noninteractive

ARG UID=500

RUN apt-get update \
    && apt-get install -y libopenal1 \
       libx11-6 \
       libplib1 \
       libcurl3 \
       libqt5widgets5 \
       libqt5qml5 \
       libopenthreads20 \
       libopenscenegraph100v5 \
       libqt5quickwidgets5 \
       strace less man alsa-base alsa-utils libpulse0 \
    && groupadd   -g 500   henrik \
    && useradd  -c "henrik"  -g 500 -u ${UID} -G audio,video henrik \
    &&  apt-get autoclean && rm -rf /var/lib/apt/* 


FROM home/nv:${NVVERSION}  as buildbase

ENV DEBIAN_FRONTEND noninteractive
ARG FGVERSION='2017.3.1'

ADD simgear-${FGVERSION}.tar.bz2 /usr/src
ADD flightgear-${FGVERSION}.tar.bz2 /usr/src

RUN apt-get update
RUN apt-get install -y cmake make g++
RUN apt-get install -y libboost-dev
#RUN apt-get install -y libgl-dev
RUN apt-get install -y libopenal-dev
RUN apt-get install -y libopenscenegraph-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y  libpulse-dev 
# libopenscenegraph-dev fucks  up the link to the proper libGL
RUN rm /usr/lib/x86_64-linux-gnu/libGL.so && ln -s libGL.so.1  /usr/lib/x86_64-linux-gnu/libGL.so
RUN mkdir /usr/src/simbuild /usr/src/fgbuild  


FROM buildbase as simbuild

ARG FGVERSION='2017.3.1'

WORKDIR /usr/src/simbuild 

RUN cmake ../simgear-${FGVERSION} -DCMAKE_BUILD_TYPE=Release
RUN make -j 5 
RUN make install 

FROM buildbase as fgbuild

ARG FGVERSION='2017.3.1'

COPY --from=simbuild /usr/local /usr/local


WORKDIR /usr/src/fgbuild 

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get install -y libplib-dev
RUN apt-get install -y libqt5opengl5-dev
RUN apt-get install -y  qtdeclarative5-dev
RUN apt-get install -y qtbase5-private-dev
RUN apt-get install -y qtdeclarative5-private-dev

RUN cmake ../flightgear-${FGVERSION} -DCMAKE_BUILD_TYPE=Release
RUN make -j 5
RUN make install





FROM runenv

VOLUME /fgfs

ENV DISPLAY :0
ENV FG_ROOT /fgfs 
ENV FG_SCENERY /fgfs/Scenery 

COPY --from=fgbuild /usr/local /usr/local
COPY pulse_config.txt /etc/pulse/client.conf
USER henrik

CMD /usr/local/bin/fgfs 
